### ISSUE TITLE
Please update pkgrel in each commit

### ISSUE THREAD

**Issue by minj** [manjaro/packages-core#24]
Sorry guys, I am not sure if this is the right place to put this feature/support request

I have experienced extreme fluctuations in battery performance in linux41 series but did not have the time to investigate it properly at the time.

Unfortunately I only now have 4.1.11+ kernels backed up due to having run paccache. So I decided to go through this repo and rebuild all the others I used, starting from 4.1.3-2.

However, I soon discovered that there are a few commits that change PKGBUILD or other files without changing pkgrel. This really hurts reproducibility.

Is there a way to match exact commit to a kernel build that reached manjaro stable at the time? Or alternatively is there a 'downgrade mirror' for manjaro kernels I could use?

Thanks

**Comment by philmmanjaro** [comment]
The first thing would be to go thru the [history](https://github.com/manjaro/packages-core/commits/master/linux41/PKGBUILD) of that package. Then you might find it more easily to check what I did with the packages so far:

[linux 4.1.3-1](https://github.com/manjaro/packages-core/commit/aa654f5938942736149b7bb2f69ea7d703753fa6) - [tarball](https://github.com/manjaro/packages-core/archive/aa654f5938942736149b7bb2f69ea7d703753fa6.zip)
[linux 4.1.3-2](https://github.com/manjaro/packages-core/blob/9b9c65f35fd8c19c14a9ebfe7f50f31e26b0bbc9/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/9b9c65f35fd8c19c14a9ebfe7f50f31e26b0bbc9.zip) - adds fix for AMD i686 CPU
[linux 4.1.4-1](https://github.com/manjaro/packages-core/blob/ee4fb10a19f7f41e9d6d13b36c0d7838326fffaf/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/ee4fb10a19f7f41e9d6d13b36c0d7838326fffaf.zip)
[linux 4.1.5-1](https://github.com/manjaro/packages-core/blob/63ea1d645b7918acad285831e2797bc544123c6d/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/63ea1d645b7918acad285831e2797bc544123c6d.zip)
[linux 4.1.6-1](https://github.com/manjaro/packages-core/blob/e77f5954e62b5a4741aa515af8e4831d7c9cddd9/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/e77f5954e62b5a4741aa515af8e4831d7c9cddd9.zip)
[linux 4.1.6-2](https://github.com/manjaro/packages-core/blob/171890b0d0ab7af9794fc0302e3216ae94994f25/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/171890b0d0ab7af9794fc0302e3216ae94994f25.zip) - try to backport OverlayFS
[linux 4.1.6-3](https://github.com/manjaro/packages-core/blob/f953af0d24ce4db2e9bb87032abd25b6b782cf30/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/f953af0d24ce4db2e9bb87032abd25b6b782cf30.zip) - proper backport of OverlayFS
[linux 4.1.7-1](https://github.com/manjaro/packages-core/blob/b40a711614508a11f9cbfdb9e0ebeac5e875915b/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/b40a711614508a11f9cbfdb9e0ebeac5e875915b.zip)
[linux 4.1.8-1](https://github.com/manjaro/packages-core/blob/3fb49e408a771bc8e1a7d39f49f02b358117ca6b/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/3fb49e408a771bc8e1a7d39f49f02b358117ca6b.zip)
[linux 4.1.8-2](https://github.com/manjaro/packages-core/commit/93cb91fd20e83dbc2a8ad0a39b0f649f57d9939a/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/93cb91fd20e83dbc2a8ad0a39b0f649f57d9939a.zip) - fix I2C controller based battery
[linux 4.1.9-1](https://github.com/manjaro/packages-core/blob/6503904f71a075f5f83e9e53148997ee0b3dbf9a/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/6503904f71a075f5f83e9e53148997ee0b3dbf9a.zip)
[linux 4.1.10-1](https://github.com/manjaro/packages-core/blob/d71243ac2eaa322eb9e4f418ebe14a2d3397bc6a/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/d71243ac2eaa322eb9e4f418ebe14a2d3397bc6a.zip)
[linux 4.1.11-1](https://github.com/manjaro/packages-core/blob/8d8e42d62c9917b8b72a3b61e86c33cc99f2bae2/linux41/PKGBUILD) - [tarball](https://github.com/manjaro/packages-core/archive/8d8e42d62c9917b8b72a3b61e86c33cc99f2bae2.zip)

After you found your starting point of your last working kernel on your box, I recommend to **[git-bisect](https://github.com/philmmanjaro/linux41/blob/master/git-bisect.txt)** the kernel **linux41** on your end. That was [what I did](https://github.com/philmmanjaro/linux41) to find the [issue](https://github.com/manjaro/packages-core/issues/14) I fixed with **4.1.3-2**.

**Comment by minj** [comment]
Yes so figured. There are 22 commits for 10 kernels I actually used (based on pacman.log) it seems. Something to keep in mind.

Anyway, the problem I now have is measuring power consumption reliably. It seems to be extremely hard to isolate all external factors to get some reproducibility. Perhaps the kernel is not at fault here.

Closing this then...
