### ISSUE TITLE
Failure with 16.06-pre2-i686 on Parallels

### ISSUE THREAD

**Issue by ylluminate** [manjaro/packages-core#33]
After installation of 16.06-pre2 on Parallels, I'm hitting a panic on first boot:

![video of panic](http://cl.ly/463Z2A1C131n/Screen%20Recording%202016-04-02%20at%2003.16%20PM.gif)

**Comment by philmmanjaro** [comment]
Seems to be a kernel problem in **4.4** series.

**Comment by philmmanjaro** [comment]
Since you're able to install it with the live media you can try to install other kernels on your installed system using [chroot](https://wiki.manjaro.org/index.php?title=Restore_the_GRUB_Bootloader#Chroot_into_your_existing_Manjaro_Installation) or try to remove the [**ucode** image](https://wiki.archlinux.org/index.php/Microcode#Grub) in **grub** from loading.

**Comment by philmmanjaro** [comment]
Is this still existing?

**Comment by philmmanjaro** [comment]
re-open if this is still exising ...
