### ISSUE TITLE
provide linux-grsec kernel as arch does

### ISSUE THREAD

**Issue by ghost** [manjaro/packages-core#52]
Manjaro have versatile offer of kernels (even RT one) so I don't see any reason to not provide this as well. There are already grsec-common, gradm and pax tools in repos so grsecurity looks as an obvious missing link here.

At first it could be just plain [copy](https://www.archlinux.org/packages/community/x86_64/linux-grsec/) from arch if you are much time constrained (it would give auto update option instead of constantly checking arch website). 

Please consider.

**Comment by budimanjojo** [comment]
If it's available in Arch repo but not in Manjaro repo, there must be a reason. :)

**Comment by zuski** [comment]
The reason is manjaro provides it's own kernels instead of using arch's

**Comment by udeved** [comment]
Do you volunteer to maintain the kernel? @zuski

**Comment by zuski** [comment]
Unfortunately no, I don't have experience and I couldn't test it on hardware beside my own (which is very open source friendly). I'm sorry.

That's why I proposed to mirror it from arch and base at their experience. Manjaro specific fixes could be added incrementally when needed.

I created [thread](https://forum.manjaro.org/t/provide-linux-grsec-kernel-as-arch-does/8200) at forum to hear from other interested users. Maybe someone more knowledgeably  would volunteer.

**Comment by udeved** [comment]
The main constraint is time, we are small team. Using arch kernels is not really an option for some reasons.

**Comment by budimanjojo** [comment]
It doesn't look that hard to maintain only the kernel as far as I look into the source, at least the developers are fast at updating the patch to match the latest kernel version (compared to rt kernel that me and oberon are facing). But the problem is the modules seem very hard to maintain, looking at the Archwiki and the available only nvidia module, and I don't see any catalyst and other modules even in AUR. I don't think anybody want the headache for this. Have you test it yet? What's your experience with the kernel?

**Comment by zuski** [comment]
External modules were exactly my concern.

My experience is good, I didn't encounter any issues on arch kernel yet (I think they provide user friendly config) but as I said above I don't use proprietary drivers.

I know that compatibility with proprietary drivers is very important for Manjaro (xorg 1.18 where are you!). On the other hand full support from maintainers with every hardware/software combination shouldn't be taken for granted or even possible.

Grsec or RT are sophisticated things so those could be treated as something extra and not for everyone. Arch and Debian sid (+ stable backports) already provide grsec and I think it's the way to go.

In the end I could live with arch kernel on my Manjaro system for now (as I live with arch xorg). Maybe someone from Manjaro staff will try to use grsec in future and solve this issue.

**Comment by philmmanjaro** [comment]
We simply won't adopt **grsec** in near future ...
